pipeline{
    agent any
    environment{
        provaN2EC = "$WORKSPACE/ProvaN2"
    }
    stages{
        stage ('Criando ambiente'){
            steps {
                echo 'Criando wrapper para gradle'
              	dir("$provaN2EC"){
				sh 'gradle wrapper'
                }
            }

        }
        stage ('Criando Testes JUnit'){
            steps{
                echo 'Criando testes JUnit'
                dir("$provaN2EC"){
				sh './gradlew test'
                }
            }
        }
        stage ('Construindo o APK'){
            steps{
                echo 'Construindo o APK'
                dir("$provaN2EC"){
				sh './gradlew assembleRelease'
                }
            }
        }
        stage ('Arquivando o APK'){
            steps{
                echo 'Arquivando o APK'
                archiveArtifacts artifacts: '**/app_debug.apk', fingerprint:false , allowEmptyArchive: true
            }
        }
    }
}